name: zip

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: zip -r mod.zip a/ test
    - run: sha1sum mod.zip > mod.zip.sha1sum

    - uses: pyTooling/Actions/releaser@main
      with:
        tag: continuous
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: mod.zip*
