name: zip

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: zip -r mod.zip a/ test
    - run: sha1sum mod.zip > mod.zip.sha1sum
    - uses: actions/upload-artifact@v3
      with:
        path: mod.zip
